version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://server:5000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=Den/25362004
      - DB_NAME=url_shortener
      - PORT=5000
      - FRONTEND_URL=http://localhost:5173
      - BASE_URL=http://localhost:5000
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    command: >
      sh -c "sleep 10 && npx sequelize-cli db:migrate && npm run start"
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Den/25362004
      - POSTGRES_DB=url_shortener
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge